Mejoras menores en App.java y Coronel.java: imports y formato
Svaldes77/Mini_Proyecto pull request #3
Opened 2024-11-05 03:55 UTC by Santy826

Esta solicitud de extracción incluye cambios menores en los archivos `Batallon/src/App.java` y `Batallon/src/soldados/Coronel.java` . Los cambios involucran principalmente la adición de imports y código comentado.

Por otra parte, se implementaron métodos necesarios para la entrada de datos mediante el menú ya existente , lo anterior relacionado con `Batallon/src/soldados/Coronel.java`

### Modificaciones en el código:

* [`Batallon/src/App.java`](diffhunk://#diff-f27a628aa406a6f57c97e8eea265a65fad19465debb56d7a2605129bb6022eadR111): Se agregó una línea en blanco para mejorar el formato.

* `Batallon/src/soldados/Coronel.java`: 
  - Se añadieron imports para `Scanner` al archivo.
  - Se añadieron métodos comentados para crear un `Coronel` y leer la entrada del usuario.

2024-11-05 12:15 UTC, Svaldes77 commented
Excelente compañero

2024-11-05 12:15 UTC, Svaldes77 approved these changes

2024-11-05 19:36 UTC, bypipe27 commented
Lo que interpreto de este pull request es que incluye varios cambios en el proyecto `Batallon`, principalmente enfocados en la adición de declaraciones de importación y métodos comentados para crear instancias de las clases `Capitan` y `Coronel`. Estos cambios buscan mejorar la funcionalidad y la legibilidad del código.

### Declaraciones de Importación:

* [`Batallon/src/soldados/Capitan.java`](diffhunk://#diff-ed1eaeaca5ad16d00be5d67ad3f53c33ec00b3a18ca53c30b4ee81a18160f60bR4-R6): Se añadieron importaciones para `Scanner`.
* [`Batallon/src/soldados/Coronel.java`](diffhunk://#diff-a50a9c144907d066dc4172649db1ea3b6473494b178ac7220dd12562ce916dedR4-R6): Se añadieron importaciones para `Scanner`.

### Métodos Comentados:

* [`Batallon/src/soldados/Capitan.java`](diffhunk://#diff-ed1eaeaca5ad16d00be5d67ad3f53c33ec00b3a18ca53c30b4ee81a18160f60bR49-R93): Se añadieron métodos estáticos comentados para crear una instancia de `Capitan` y métodos auxiliares para leer la entrada del usuario.
* [`Batallon/src/soldados/Coronel.java`](diffhunk://#diff-a50a9c144907d066dc4172649db1ea3b6473494b178ac7220dd12562ce916dedR51-R92): Se añadieron métodos estáticos comentados para crear una instancia de `Coronel` y métodos auxiliares para leer la entrada del usuario.

2024-11-07 02:13 UTC, bypipe27 requested changes
Compañero @Santy826  revisando un poco más a fondo el desarrollo de lo que añadiste te quería hacer la observación en unos métodos que agregaste. 

 
   

`// private static int leerEntero(Scanner scanner, String mensaje) {
    //     System.out.print(mensaje);
    //     while (!scanner.hasNextInt()) {
    //         System.out.println("Por favor, ingrese un número entero válido.");
    //         scanner.next(); // Consumir la entrada no válida
    //         System.out.print(mensaje);
    //     }
    //     return scanner.nextInt();
    // }

    // private static String leerCadena(Scanner scanner, String mensaje) {
    //     System.out.print(mensaje);
    //     return scanner.nextLine();
    // }

    // private static Nivel_militar leerRango(Scanner scanner, String mensaje) {
    //     System.out.print(mensaje);
    //     while (true) {
    //         try {
    //             String input = scanner.nextLine().toUpperCase();
    //             return Nivel_militar.valueOf(input);
    //         } catch (IllegalArgumentException e) {
    //             System.out.println("Rango no válido. Por favor, ingrese uno de los siguientes: SOLDADO, SOLDADO_RASO, TENIENTE, CORONEL.");
    //             System.out.print(mensaje);
    //         }
    //     `


Siento que se pueden manejar de manera, si quieres revisa el aporte de Samuel para que sea más limpio

2024-11-07 02:59 UTC, bypipe27 approved these changes
Magnifico trabajo compañero, y gracias por la comentar las líneas que se entregara en un futuro.

2024-11-07 03:00 UTC, merged